export const clinic = {
  name: "Dr. Ameen's Smile Studio",
  phone: "+91 73063 08876",
  tel: "+917306308876",
  hours: "Monday–Saturday · 10:00 AM–7:00 PM",
  address: "Near Erapund Juma Masjid, Madrassa Bazar, South Koduvally, Koduvally, Kerala 673572, India",
  maps: "https://www.google.com/maps/search/?api=1&query=Dr.+Ameen%27s+Smile+Studio+South+Koduvally+Kerala",
};

export const whatsapp = (interest?: string) => `https://wa.me/917306308876?text=${encodeURIComponent(`Hello Dr. Ameen's Smile Studio, I would like to enquire about ${interest ? `${interest.toLowerCase()} and an appointment` : 'an appointment'}.`)}`;

export type Treatment = {
  slug: string; name: string; short: string; intro: string; overview: string;
  suitable: string; process: string[]; expectations: string; faqs: {q: string; a: string}[];
};

export const treatments: Treatment[] = [
  { slug: "smile-designing", name: "Smile Designing", short: "A considered approach to the details that make a smile yours.", intro: "A smile begins with a conversation.", overview: "Smile designing is a broad term for planning changes to the appearance of a smile. A dentist can discuss your concerns, assess your oral health and explain which options may be appropriate for you.", suitable: "People curious about the appearance of their teeth or smile can ask for an assessment. The right approach depends on individual dental health and goals.", process: ["Discuss what you would like to change", "Have your teeth and oral health assessed", "Review suitable options and next steps together"], expectations: "A consultation is the starting point. Any proposed treatment, timeline and expected result depend on a clinical assessment.", faqs: [{q:"Is smile designing one treatment?",a:"No. It is a planning approach that may involve different dental treatments depending on your needs."},{q:"Will I know the options at my first visit?",a:"A dentist can discuss possibilities after assessing your teeth and oral health."}] },
  { slug: "orthodontics", name: "Orthodontics", short: "Explore options for the alignment of teeth and bite.", intro: "Alignment, considered carefully.", overview: "Orthodontic treatment aims to move teeth into improved positions over time. An assessment helps determine whether treatment is suitable and which approach may be considered.", suitable: "People with concerns about tooth alignment or bite may wish to discuss orthodontic options with a dental professional.", process: ["Discuss your alignment concerns", "Assess teeth, gums and bite", "Review possible approaches and follow-up needs"], expectations: "Treatment needs and duration vary. Your dentist can explain a proposed plan after assessment.", faqs: [{q:"How long does orthodontic treatment take?",a:"It varies with the individual and the type of treatment. A clinical assessment is needed for a personal estimate."},{q:"Are aligners the only option?",a:"No. Different orthodontic approaches may be discussed depending on clinical suitability."}] },
  { slug: "clear-aligners", name: "Clear Aligners", short: "A discreet route to discussing tooth alignment.", intro: "A clearer path starts with clarity.", overview: "Clear aligners are removable trays designed to move teeth gradually according to a planned sequence. They are not suitable for every case, so professional assessment matters.", suitable: "People interested in a removable alignment option can discuss their goals and suitability at a consultation.", process: ["Assess your teeth and bite", "Discuss whether aligners may suit your case", "Review the proposed plan and ongoing checks"], expectations: "Wear requirements, check-ins and duration differ by case. Your dentist will explain the practical commitments involved.", faqs: [{q:"Can everyone use clear aligners?",a:"No. Suitability depends on your dental health and alignment needs."},{q:"How long would I need aligners?",a:"There is no universal timeline. A dentist can discuss an estimate after assessment."}] },
  { slug: "veneers", name: "Veneers", short: "Understand one option for changing the look of a tooth.", intro: "The details deserve attention.", overview: "A veneer is a thin covering placed on the front of a tooth. It may be considered for certain appearance concerns, depending on oral health and the desired change.", suitable: "People considering changes to the shape, colour or appearance of teeth may ask whether veneers are appropriate.", process: ["Talk through your goals", "Assess teeth and discuss materials", "Review preparation, placement and care"], expectations: "Veneers require maintenance and may not be the right choice for every tooth. Ask about alternatives and long-term care before deciding.", faqs: [{q:"Do veneers need care?",a:"Yes. Good oral hygiene and regular dental reviews remain important."},{q:"Are veneers right for every tooth?",a:"No. A dentist needs to assess your teeth, gums and goals first."}] },
  { slug: "dental-implants", name: "Dental Implants", short: "A conversation about options for a missing tooth.", intro: "A thoughtful next step after tooth loss.", overview: "A dental implant is a replacement tooth root placed in the jaw to support a restoration. Suitability depends on oral and general health, available bone and other factors.", suitable: "People with one or more missing teeth can ask about implants and other replacement options.", process: ["Assess oral health and replacement needs", "Discuss suitability and the proposed stages", "Plan placement, healing and restoration if appropriate"], expectations: "Implant care takes place over stages; timing and outcomes vary. A dentist should explain risks, alternatives and maintenance for your case.", faqs: [{q:"Can anyone have a dental implant?",a:"No. Suitability must be determined by a dental professional after assessment."},{q:"Is an implant completed in one visit?",a:"Implant treatment commonly involves several stages. Your plan and timing will be individual."}] },
  { slug: "root-canal-treatment", name: "Root Canal Treatment", short: "Learn what it means to treat infection inside a tooth.", intro: "Understanding the path to preserving a tooth.", overview: "Root canal treatment removes inflamed or infected tissue from inside a tooth, then cleans and seals the space. A dentist can determine whether it is appropriate after examination.", suitable: "Persistent tooth pain, sensitivity or swelling should be assessed by a dental professional. These symptoms can have different causes.", process: ["Examine the tooth and discuss findings", "Clean and seal the inner tooth if indicated", "Discuss restoration and follow-up care"], expectations: "Aftercare and any further restoration depend on the tooth. Seek prompt dental advice for swelling, severe pain or worsening symptoms.", faqs: [{q:"Does tooth pain always mean I need a root canal?",a:"No. Tooth pain has several possible causes. An examination is needed to determine what is happening."},{q:"What if I have facial swelling?",a:"Seek prompt professional assessment, particularly if symptoms are severe or worsening."}] },
];

export const commonFaqs = [
  {q:"How do I request an appointment?",a:"Call the clinic or send an enquiry on WhatsApp. The clinic can confirm availability directly with you."},
  {q:"Where is the clinic?",a:"Near Erapund Juma Masjid, Madrassa Bazar, South Koduvally, Koduvally, Kerala 673572."},
  {q:"When is the clinic open?",a:"The publicly listed hours are Monday to Saturday, 10:00 AM to 7:00 PM. Please call to confirm before visiting, especially on holidays."},
  {q:"Can I ask about treatment costs?",a:"Yes. Contact the clinic directly for current pricing and an estimate appropriate to your needs."},
  {q:"Can I get advice for a dental emergency?",a:"Call a dental professional promptly for urgent symptoms. For serious or rapidly worsening symptoms, seek urgent medical care."},
];
