import { Link } from '@tanstack/react-router';
import { ArrowUpRight, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { clinic, whatsapp, type Treatment } from '@/lib/site-data';

export function Eyebrow({children}: {children: React.ReactNode}) { return <p className="eyebrow">{children}</p> }
export function BookingLinks({interest, light=false}: {interest?: string; light?: boolean}) { return <div className="flex flex-wrap items-center gap-5"><Button asChild className={light ? 'action action-light' : 'action'}><Link to="/contact" search={{interest: interest ?? ''}}>Book a consultation <ArrowUpRight /></Link></Button><a className={`text-link ${light ? 'text-primary-foreground' : ''}`} href={whatsapp(interest)} target="_blank" rel="noopener noreferrer">WhatsApp us <ArrowUpRight size={17}/></a></div> }
export function SectionHeading({index, label, title, copy}: {index:string; label:string; title:string; copy?:string}) { return <div className="section-heading"><div className="flex items-center gap-3"><span className="index-mark">{index}</span><Eyebrow>{label}</Eyebrow></div><div><h2 className="display-heading">{title}</h2>{copy && <p className="section-copy">{copy}</p>}</div></div> }
export function TreatmentList({items}: {items: Treatment[]}) { return <div className="treatment-list">{items.map((t,i)=><Link key={t.slug} to="/treatments/$slug" params={{slug:t.slug}} className="treatment-row group"><span className="row-number">0{i+1}</span><span className="row-main"><strong>{t.name}</strong><span>{t.short}</span></span><span className="row-arrow"><ArrowUpRight size={24}/></span></Link>)}</div> }
export function ContactBand() { return <section className="contact-band"><div className="container-wide contact-band-inner"><div><Eyebrow>THE NEXT STEP</Eyebrow><h2>Let’s begin with<br/><em>a conversation.</em></h2></div><div><p>Tell us what you have in mind. The clinic can help you arrange a time to talk.</p><BookingLinks light /></div></div></section> }
export function LocationBlock() { return <section className="location-section"><div className="container-wide location-grid"><div><Eyebrow>FIND US</Eyebrow><h2 className="display-heading">Close to home.<br/><em>Easy to find.</em></h2><p className="section-copy">Near Erapund Juma Masjid<br/>Madrassa Bazar, South Koduvally<br/>Koduvally, Kerala 673572</p><p className="hours-line">{clinic.hours}</p><a className="text-link" href={clinic.maps} target="_blank" rel="noopener noreferrer">Get directions <ArrowUpRight size={18}/></a></div><a href={clinic.maps} target="_blank" rel="noopener noreferrer" className="map-art" aria-label="Open directions to Dr. Ameen's Smile Studio in Google Maps"><div className="map-grid"/><div className="map-road road-one"/><div className="map-road road-two"/><div className="map-pin"><span>✳</span><strong>Dr. Ameen's<br/>Smile Studio</strong><small>South Koduvally</small></div><span className="map-corner">KOZHIKODE DISTRICT — KERALA <ArrowRight size={16}/></span></a></div></section> }
export function FAQList({items}: {items:{q:string;a:string}[]}) { return <div className="faq-list">{items.map((item,i)=><details key={item.q}><summary><span className="row-number">0{i+1}</span><span>{item.q}</span><span className="faq-plus">+</span></summary><p>{item.a}</p></details>)}</div> }
export function PageIntro({label,title,copy}: {label:string;title:string;copy:string}) { return <section className="page-intro container-wide"><Eyebrow>{label}</Eyebrow><h1>{title}</h1><p>{copy}</p></section> }
