import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowUpRight, Menu, X, Phone, MessageCircle, CalendarDays } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { clinic, whatsapp, treatments } from '@/lib/site-data';

const links = [{to:'/treatments',label:'Treatments'},{to:'/treatments/smile-designing',label:'Smile design'},{to:'/about',label:'About'},{to:'/gallery',label:'Gallery'},{to:'/reviews',label:'Reviews'},{to:'/faq',label:'FAQ'},{to:'/contact',label:'Contact'}];
export function SiteHeader() {
 const [open,setOpen]=useState(false);
 return <><header className="site-header"><div className="container-wide header-inner"><Link to="/" className="brand" onClick={()=>setOpen(false)} aria-label="Dr. Ameen's Smile Studio home"><span className="brand-symbol" aria-hidden="true">a<span className="symbol-arc"/></span><span className="brand-name">DR. AMEEN'S <small>SMILE STUDIO</small></span></Link><nav className="desktop-nav" aria-label="Main navigation">{links.map(l=><Link key={l.to} to={l.to} className="nav-link" activeProps={{className:'nav-link active'}}>{l.label}</Link>)}</nav><div className="header-actions"><Button asChild className="header-book"><Link to="/contact" search={{interest:''}}>Book consultation <ArrowUpRight size={16}/></Link></Button><Button variant="ghost" size="icon" className="menu-button" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div></div></header>{open && <nav className="mobile-menu" aria-label="Mobile navigation">{links.map((l,i)=><Link key={l.to} to={l.to} onClick={()=>setOpen(false)}><small>0{i+1}</small>{l.label}<ArrowUpRight size={20}/></Link>)}</nav>}</>
}
export function SiteFooter() { return <footer className="site-footer"><div className="container-wide footer-main"><div><Link to="/" className="footer-brand">Dr. Ameen's<br/><em>Smile Studio.</em></Link><p>Thoughtful dental care in South Koduvally.</p></div><div><h3>EXPLORE</h3><Link to="/treatments">Treatments</Link><Link to="/about">About</Link><Link to="/gallery">Gallery</Link><Link to="/reviews">Reviews</Link><Link to="/faq">Questions</Link></div><div><h3>TREATMENTS</h3>{treatments.map(t=><Link key={t.slug} to="/treatments/$slug" params={{slug:t.slug}}>{t.name}</Link>)}</div><div><h3>VISIT & CONNECT</h3><p>{clinic.address}</p><a href={`tel:${clinic.tel}`}>{clinic.phone}</a><a href={whatsapp()} target="_blank" rel="noopener noreferrer">WhatsApp <ArrowUpRight size={14}/></a><a href={clinic.maps} target="_blank" rel="noopener noreferrer">Get directions <ArrowUpRight size={14}/></a><p>{clinic.hours}</p></div></div><div className="container-wide footer-bottom"><span>© {new Date().getFullYear()} Dr. Ameen's Smile Studio</span><div><Link to="/privacy">Privacy</Link><Link to="/medical-disclaimer">Medical disclaimer</Link></div><span>South Koduvally, Kerala</span></div></footer> }
export function MobileActions() {return <div className="mobile-actions"><a href={`tel:${clinic.tel}`}><Phone size={18}/>Call</a><a href={whatsapp()} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/>WhatsApp</a><Link to="/contact" search={{interest:''}}><CalendarDays size={18}/>Book</Link></div>}
